CREATE TABLE if not exists tasks
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    description  VARCHAR(255),
    due_date DATE,
    priority VARCHAR(255),
    user_id INTEGER                                  NOT NULL,
    category_id INTEGER  NOT NULL,
    CONSTRAINT pk_task PRIMARY KEY (id),
    CONSTRAINT FK_TASK_ON_USERS FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ,
    CONSTRAINT FK_TASK_ON_CATEGORIES FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL
);