CREATE TABLE photos
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      INTEGER,
    photo_url    VARCHAR(255),
    photo_binary OID,
    CONSTRAINT pk_photos PRIMARY KEY (id),
    CONSTRAINT FK_TASK_ON_USERS FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);