CREATE TABLE IF NOT EXISTS password_reset_tokens
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token            VARCHAR(255) NOT NULL,
    expiration_date  TIMESTAMP NOT NULL,
    user_id          INTEGER NOT NULL,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id),
    CONSTRAINT fk_user_on_password_reset_tokens FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
