CREATE TABLE if not exists messages
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER,
    description VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id),
    CONSTRAINT FK_TASK_ON_USERS FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
